### ISSUE TITLE
System Setup Tutorial erratum

### ISSUE THREAD

**Issue by GrantEdwards** [renesas-rz/rzn1_linux-4.19_bsp#1]
> #### 6.2.2 Flash
>
> Download to QSPI the precompiled RZ/N linux kernel uImage from the DVD. You can find it on
> the DVD at ./Linux\kernel\binaries\core-image-minimal-rzn1.squashfs.

The sentence above doesn't make sense.  Is it supposed to be talking about the Linux kernel uImage or the root squashfs image?

Backslashes in a path for a tutorial on how to do things on Linux?  That's embarassing.

**Comment by CarlStenquist** [comment]
Oh, excuse me. 
Yes of course it's the root file system. I'll move that section. Should have been 6.3, not 6.2.2. I'll repost it.

I wrote this doc. totally on my own initiative so please be nice.
